import { Dish, Order, Restaurant } from "../types/types";
export const defaultRestaurant: Restaurant = {
  name: "Claro",
  chef: "Ran Shmueli",
  pictureUrl: "../assets/images/restaurants/claro.png",
  openNow: false,
  location: "",
  rating: 1,
  mostPopular: false,
  newRestaurant: false,
  restaurantDishes: [
    {
      name: "Pad Ki Mao",
      pictureUrl: "../assets/images/dishes/padKiMao.png",
      description: "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
      price: 88,
      signatureDish: true,
      foodIcon: "../assets/images/spicyIcon.svg",
      mealType: "dinner",
      keyId: "9",
    },
    {
      name: "Garbanzo Frito",
      pictureUrl: "../assets/images/dishes/garbanzoFrito.png",
      description: "Polenta fingers, veal cheek, magic chili cured lemon cream, yellow laksa",
      price: 98,
      signatureDish: true,
      foodIcon: "../assets/images/spicyIcon.svg",
      mealType: "breakfast",
      keyId: "10",
    },
    {
      name: "Smoked Pizza",
      pictureUrl: "../assets/images/dishes/smokedPizza.png",
      description: "Basil dough, cashew butter , demi-glace, bison & radish",
      price: 98,
      signatureDish: true,
      foodIcon: "../assets/images/veganIcon.svg",
      mealType: "breakfast",
      keyId: "11",
    },
    {
      name: "Ta Ma La Ko",
      pictureUrl: "../assets/images/dishes/taMaLaKo.png",
      description: "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
      price: 65,
      signatureDish: false,
      foodIcon: "../assets/images/spicyIcon.svg",
      mealType: "lunch",
      keyId: "12",
    },
    {
      name: "Red Farm",
      pictureUrl: "../assets/images/dishes/redFarm.png",
      description: "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
      price: 65,
      signatureDish: false,
      foodIcon: "../assets/images/spicyIcon.svg",
      mealType: "lunch",
      keyId: "13",
    },
    {
      name: "Pad Ki Mao 1",
      pictureUrl: "../assets/images/dishes/padKiMaoOne.png",
      description: "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
      price: 65,
      signatureDish: false,
      foodIcon: "../assets/images/spicyIcon.svg",
      mealType: "breakfast",
      keyId: "14",
    },
    {
      name: "Red Farm",
      pictureUrl: "../assets/images/dishes/padKiMaoThree.png",
      description: "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
      price: 88,
      signatureDish: true,
      foodIcon: "../assets/images/spicyIcon.svg",
      mealType: "breakfast",
      keyId: "15",
    },
    {
      name: "Pad Ki Mao 2",
      pictureUrl: "../assets/images/dishes/padKiMaoTwo.png",
      description: "Tofu, Spekkoek Peanuts, Spicy Manis, Pear Yakitori",
      price: 98,
      signatureDish: true,
      foodIcon: "../assets/images/spicyIcon.svg",
      mealType: "dinner",
      keyId: "16",
    },
  ],
  priceRange: [88, 250],
  keyId: "0",
};

export const defaultDish: Dish = {
  name: "Pad Ki Mao",
  pictureUrl: "../assets/images/dishes/padKiMao.png",
  description: "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
  price: 88,
  signatureDish: true,
  foodIcon: "../assets/images/spicyIcon.svg",
  mealType: "breakfast",
  restaurant: "Claro",
  keyId: "9",
};

export const defaultOrder: Order = {
  restaurantName: defaultRestaurant.name,
  dishes: defaultRestaurant.restaurantDishes,
};
